FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion

RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh

ENV PATH /opt/conda/bin:$PATH

# Java
RUN apt-get -y install default-jre 

# H2o deps
RUN pip install requests tabulate six future colorama

# H2o
RUN pip install h2o==3.26.0.3

# Pandas
RUN pip install pandas==0.23.4

# XGBoost
RUN apt-get update --fix-missing && \
    apt-get -y install gcc g++ make && \
    conda install -y libgcc

# Download cmake sh
RUN apt-get install -y wget libssl-dev && \
    wget https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-linux-x86_64.sh && \
    cp cmake-3.22.1-linux-x86_64.sh /opt/ && \
    chmod +x /opt/cmake-3.22.1-linux-x86_64.sh && \
    bash /opt/cmake-3.22.1-linux-x86_64.sh --skip-license && \
    ln -s /opt/cmake-3.22.1-linux-x86_64/bin/* /usr/local/bin && \
    cmake --version

RUN pip install --upgrade pip && \
    conda uninstall -y numpy && \
    pip uninstall opencv-python

COPY requirements.txt .
RUN pip install --ignore-installed certifi --no-cache-dir -r requirements.txt && \
    pip install -U scipy && \
    pip uninstall -y opencv-python-headless && \
    pip install opencv-python-headless==4.5.1.48

RUN mkdir src
WORKDIR /src
CMD ["python3"]
